### ISSUE TITLE
Add runtime name and version metrics

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/polkadot-runtime-prom-exporter#15]
It would be really useful to have the runtime specName and specVersion exposed as metrics. This value is available in the chain state under `system.lastRuntimeUpgrade`.

This would let us create Prometheus alerts on runtime version changes.

**Comment by gilles437** [comment]
Solved in PR https://github.com/paritytech/polkadot-runtime-prom-exporter/pull/14/
